export const SET_AUTOMATIC_RECORDING = 'SET_AUTOMATIC_RECORDING';
export const SET_AUTOMATIC_RECORDING_SUCCESS =
  'SET_AUTOMATIC_RECORDING_SUCCESS';
export const SET_AUTOMATIC_RECORDING_FAILURE =
  'SET_AUTOMATIC_RECORDING_FAILURE';
